apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 945832859787.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 945832859787.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: da8e5748
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
